function generateReadme(config) {
  return `# ${config.projectName} — ${config.envName} Sandbox

Generated by **GoneOps** DevOps DX Platform.

> This is a local development sandbox — not production-safe. Secrets are stored in plaintext.

## Stack
- **Runtime:** Node.js 20 (Alpine)
- **Database:** PostgreSQL 15 — \`${config.dbName}\`
- **Cache:** Redis 7
- **Message Queue:** RabbitMQ 3.12

## URLs & Ports
| Service | Host Port | Container Port |
|---------|-----------|----------------|
| Web API | ${config.webPort} | 8080 |
| PostgreSQL | ${config.dbPort} | 5432 |
| Redis | ${config.redisPort} | 6379 |
| RabbitMQ | ${config.mqPort} | 5672 |

## Database
- **Name:** \`${config.dbName}\`
- **User:** \`${config.dbUser}\`
- **Password:** \`${config.dbPass}\`

## Cache
- **Host:** \`${config.redisName}\`

## Message Queue
- **User:** \`${config.mqUser}\`
- **Password:** \`${config.mqPass}\`

## Run Commands
\`\`\`bash
cd ${config.workingDir}
npm install
npm run dev
\`\`\`

## Docker
\`\`\`bash
cd ${config.workingDir}
docker compose up -d
\`\`\`

## API Endpoints
- **GET /health** — Health check
- **GET /api/test** — Full connection test (PostgreSQL, Redis, RabbitMQ)

## Test API
\`\`\`bash
curl http://localhost:${config.webPort}/health
curl http://localhost:${config.webPort}/api/test
\`\`\`

---
Generated by GoneOps MVP | ${new Date().toISOString().split('T')[0]}
`;
}

module.exports = { generateReadme };
