import { BadRequestException, Injectable } from "@nestjs/common";
import {
  ArchitecturePreset,
  GenerateProjectRequest,
  GenerateProjectResponse,
  ProjectStack,
  ProjectTemplate
} from "./project-generator.types";

const STACKS: ProjectStack[] = ["next-nest", "api-worker", "static-site"];
const TEMPLATES: ProjectTemplate[] = ["saas-dashboard", "internal-tool", "service-api"];
const ARCHITECTURE_PRESETS: ArchitecturePreset[] = ["local-first", "api-first", "event-driven"];

@Injectable()
export class ProjectGeneratorService {
  getOptions() {
    return {
      stacks: STACKS,
      templates: TEMPLATES,
      architecturePresets: ARCHITECTURE_PRESETS
    };
  }

  generate(request: GenerateProjectRequest): GenerateProjectResponse {
    const name = this.normalizeName(request.name);
    const stack = this.pickOption("stack", request.stack, STACKS, "next-nest");
    const template = this.pickOption("template", request.template, TEMPLATES, "internal-tool");
    const architecturePreset = this.pickOption(
      "architecturePreset",
      request.architecturePreset,
      ARCHITECTURE_PRESETS,
      "local-first"
    );
    const slug = this.toSlug(name);

    const structure = [
      `${slug}/README.md`,
      `${slug}/docker-compose.yml`,
      `${slug}/.env.example`,
      `${slug}/apps/web/src/main.ts`,
      `${slug}/apps/api/src/main.ts`,
      `${slug}/docs/architecture.md`,
      `${slug}/docs/context-diagram.md`,
      `${slug}/docs/system-diagram.md`,
      `${slug}/docs/deployment-diagram.md`,
      `${slug}/docs/api-contract.md`,
      `${slug}/tasks/README.md`
    ];

    const files = [
      {
        path: `${slug}/README.md`,
        content: this.renderReadme(name, stack, template, architecturePreset)
      },
      {
        path: `${slug}/docker-compose.yml`,
        content: this.renderDockerCompose(slug)
      },
      {
        path: `${slug}/.env.example`,
        content: "APP_NAME=example-app\nPOSTGRES_DB=example_app\nPOSTGRES_USER=example_user\nPOSTGRES_PASSWORD=change-me-locally\n"
      },
      {
        path: `${slug}/docs/architecture.md`,
        content: this.renderArchitecture(name, stack, architecturePreset)
      },
      {
        path: `${slug}/docs/context-diagram.md`,
        content: this.renderContextDiagram(name, slug, architecturePreset)
      },
      {
        path: `${slug}/docs/system-diagram.md`,
        content: this.renderSystemDiagram(name, slug, stack)
      },
      {
        path: `${slug}/docs/deployment-diagram.md`,
        content: this.renderDeploymentDiagram(name, slug, architecturePreset)
      },
      {
        path: `${slug}/docs/api-contract.md`,
        content: this.renderApiContract(name, slug, stack)
      }
    ];

    this.validateGeneratedFiles(files);

    return {
      project: { name, slug, stack, template, architecturePreset },
      structure,
      files,
      validation: {
        valid: true,
        checks: [
          "project name normalized",
          "stack/template/preset allowlisted",
          "generated paths are relative",
          "required files generated",
          "mermaid diagrams generated",
          "api contract generated",
          "secret placeholders only"
        ]
      }
    };
  }

  private normalizeName(name?: string): string {
    const normalized = (name ?? "GoneOps Starter").trim().replace(/\s+/g, " ");
    if (normalized.length < 3 || normalized.length > 80) {
      throw new BadRequestException("Project name must be between 3 and 80 characters.");
    }
    if (!/^[A-Za-z0-9][A-Za-z0-9 _-]*$/.test(normalized)) {
      throw new BadRequestException("Project name may only contain letters, numbers, spaces, underscores, and hyphens.");
    }
    return normalized;
  }

  private pickOption<T extends string>(label: string, value: T | undefined, allowed: readonly T[], fallback: T): T {
    const selected = value ?? fallback;
    if (!allowed.includes(selected)) {
      throw new BadRequestException(`Unsupported ${label}: ${selected}`);
    }
    return selected;
  }

  private toSlug(name: string): string {
    return name
      .toLowerCase()
      .replace(/[^a-z0-9]+/g, "-")
      .replace(/^-+|-+$/g, "");
  }

  private renderReadme(name: string, stack: ProjectStack, template: ProjectTemplate, architecturePreset: ArchitecturePreset): string {
    return `# ${name}\n\nGenerated by GoneOps Project Generator.\n\n## Stack\n\n- ${stack}\n\n## Template\n\n- ${template}\n\n## Architecture Preset\n\n- ${architecturePreset}\n\n## Local Start\n\n\`\`\`bash\ndocker compose up -d\n\`\`\`\n`;
  }

  private renderDockerCompose(slug: string): string {
    return `services:\n  postgres:\n    image: postgres:16-alpine\n    environment:\n      POSTGRES_DB: \${POSTGRES_DB:-${slug.replace(/-/g, "_")}}\n      POSTGRES_USER: \${POSTGRES_USER:-app}\n      POSTGRES_PASSWORD: \${POSTGRES_PASSWORD:-change-me-locally}\n    ports:\n      - "5432:5432"\n`;
  }

  private renderArchitecture(name: string, stack: ProjectStack, architecturePreset: ArchitecturePreset): string {
    return `# ${name} Architecture\n\nPreset: ${architecturePreset}\n\nStack: ${stack}\n\n## Components\n\n- Web application\n- API service\n- PostgreSQL metadata store\n\n## Generated Design Docs\n\n- [Context diagram](./context-diagram.md)\n- [System diagram](./system-diagram.md)\n- [Deployment diagram](./deployment-diagram.md)\n- [API contract](./api-contract.md)\n`;
  }

  private renderContextDiagram(name: string, slug: string, architecturePreset: ArchitecturePreset): string {
    return `# ${name} Context Diagram\n\nArchitecture preset: ${architecturePreset}\n\n\`\`\`mermaid\nflowchart LR\n  Developer[Developer] --> Platform[${name} / ${slug}]\n  Platform --> Browser[Web UI]\n  Platform --> Api[API Service]\n  Api --> Database[(PostgreSQL)]\n  Api --> Observability[Structured Logs and Traces]\n\`\`\`\n`;
  }

  private renderSystemDiagram(name: string, slug: string, stack: ProjectStack): string {
    return `# ${name} System Diagram\n\nStack: ${stack}\n\n\`\`\`mermaid\nflowchart TB\n  subgraph ${this.toMermaidId(slug)}[${name}]\n    Web[apps/web] --> Api[apps/api]\n    Api --> Db[(PostgreSQL)]\n    Api --> Queue[(Async Jobs)]\n  end\n  Web --> Health[Health and readiness checks]\n\`\`\`\n`;
  }

  private renderDeploymentDiagram(name: string, slug: string, architecturePreset: ArchitecturePreset): string {
    return `# ${name} Deployment Diagram\n\nLocal-first deployment target for ${architecturePreset}.\n\n\`\`\`mermaid\nflowchart TB\n  Host[Developer Workstation] --> Compose[Docker Compose Project: ${slug}]\n  Compose --> Web[Web Container]\n  Compose --> Api[API Container]\n  Compose --> Postgres[(PostgreSQL Volume)]\n  Compose --> Logs[Local Logs]\n\`\`\`\n`;
  }

  private renderApiContract(name: string, slug: string, stack: ProjectStack): string {
    return `# ${name} API Contract\n\nGenerated safe starter contract for ${slug} (${stack}).\n\n## Endpoints\n\n| Method | Path | Purpose |\n| --- | --- | --- |\n| GET | /health | Liveness check |\n| GET | /ready | Dependency readiness check |\n| GET | /live | Runtime liveness check |\n\n## Response Envelope\n\n\`\`\`json\n{\n  "status": "ok",\n  "service": "${slug}",\n  "trace_id": "generated-at-runtime"\n}\n\`\`\`\n`;
  }

  private toMermaidId(value: string): string {
    return value.replace(/[^A-Za-z0-9]/g, "_");
  }

  private validateGeneratedFiles(files: { path: string; content: string }[]) {
    const required = [
      "README.md",
      "docker-compose.yml",
      ".env.example",
      "docs/architecture.md",
      "docs/context-diagram.md",
      "docs/system-diagram.md",
      "docs/deployment-diagram.md",
      "docs/api-contract.md"
    ];
    for (const suffix of required) {
      if (!files.some((file) => file.path.endsWith(suffix))) {
        throw new BadRequestException(`Generated output missing ${suffix}`);
      }
    }
    for (const file of files) {
      if (file.path.startsWith("/") || file.path.includes("..")) {
        throw new BadRequestException(`Unsafe generated path: ${file.path}`);
      }
      if (/(ghp_|sk-|BEGIN (RSA|OPENSSH|PRIVATE) KEY)/.test(file.content)) {
        throw new BadRequestException(`Generated file appears to contain a secret: ${file.path}`);
      }
      if (file.path.includes("diagram") && !file.content.includes("```mermaid")) {
        throw new BadRequestException(`Generated diagram file is missing a Mermaid block: ${file.path}`);
      }
    }
  }
}
