import { BadRequestException, Injectable } from "@nestjs/common";
import {
  ArchitecturePreset,
  GenerateProjectRequest,
  GenerateProjectResponse,
  ProjectStack,
  ProjectTemplate
} from "./project-generator.types";

const STACKS: ProjectStack[] = ["next-nest", "api-worker", "static-site"];
const TEMPLATES: ProjectTemplate[] = ["saas-dashboard", "internal-tool", "service-api"];
const ARCHITECTURE_PRESETS: ArchitecturePreset[] = ["local-first", "api-first", "event-driven"];

@Injectable()
export class ProjectGeneratorService {
  getOptions() {
    return {
      stacks: STACKS,
      templates: TEMPLATES,
      architecturePresets: ARCHITECTURE_PRESETS
    };
  }

  generate(request: GenerateProjectRequest): GenerateProjectResponse {
    const name = this.normalizeName(request.name);
    const stack = this.pickOption("stack", request.stack, STACKS, "next-nest");
    const template = this.pickOption("template", request.template, TEMPLATES, "internal-tool");
    const architecturePreset = this.pickOption(
      "architecturePreset",
      request.architecturePreset,
      ARCHITECTURE_PRESETS,
      "local-first"
    );
    const slug = this.toSlug(name);

    const structure = [
      `${slug}/README.md`,
      `${slug}/docker-compose.yml`,
      `${slug}/.env.example`,
      `${slug}/apps/web/src/main.ts`,
      `${slug}/apps/api/src/main.ts`,
      `${slug}/docs/architecture.md`,
      `${slug}/tasks/README.md`
    ];

    const files = [
      {
        path: `${slug}/README.md`,
        content: this.renderReadme(name, stack, template, architecturePreset)
      },
      {
        path: `${slug}/docker-compose.yml`,
        content: this.renderDockerCompose(slug)
      },
      {
        path: `${slug}/.env.example`,
        content: "APP_NAME=example-app\nPOSTGRES_DB=example_app\nPOSTGRES_USER=example_user\nPOSTGRES_PASSWORD=change-me-locally\n"
      },
      {
        path: `${slug}/docs/architecture.md`,
        content: this.renderArchitecture(name, stack, architecturePreset)
      }
    ];

    this.validateGeneratedFiles(files);

    return {
      project: { name, slug, stack, template, architecturePreset },
      structure,
      files,
      validation: {
        valid: true,
        checks: [
          "project name normalized",
          "stack/template/preset allowlisted",
          "generated paths are relative",
          "required files generated",
          "secret placeholders only"
        ]
      }
    };
  }

  private normalizeName(name?: string): string {
    const normalized = (name ?? "GoneOps Starter").trim().replace(/\s+/g, " ");
    if (normalized.length < 3 || normalized.length > 80) {
      throw new BadRequestException("Project name must be between 3 and 80 characters.");
    }
    if (!/^[A-Za-z0-9][A-Za-z0-9 _-]*$/.test(normalized)) {
      throw new BadRequestException("Project name may only contain letters, numbers, spaces, underscores, and hyphens.");
    }
    return normalized;
  }

  private pickOption<T extends string>(label: string, value: T | undefined, allowed: readonly T[], fallback: T): T {
    const selected = value ?? fallback;
    if (!allowed.includes(selected)) {
      throw new BadRequestException(`Unsupported ${label}: ${selected}`);
    }
    return selected;
  }

  private toSlug(name: string): string {
    return name
      .toLowerCase()
      .replace(/[^a-z0-9]+/g, "-")
      .replace(/^-+|-+$/g, "");
  }

  private renderReadme(name: string, stack: ProjectStack, template: ProjectTemplate, architecturePreset: ArchitecturePreset): string {
    return `# ${name}\n\nGenerated by GoneOps Project Generator.\n\n## Stack\n\n- ${stack}\n\n## Template\n\n- ${template}\n\n## Architecture Preset\n\n- ${architecturePreset}\n\n## Local Start\n\n\`\`\`bash\ndocker compose up -d\n\`\`\`\n`;
  }

  private renderDockerCompose(slug: string): string {
    return `services:\n  postgres:\n    image: postgres:16-alpine\n    environment:\n      POSTGRES_DB: \${POSTGRES_DB:-${slug.replace(/-/g, "_")}}\n      POSTGRES_USER: \${POSTGRES_USER:-app}\n      POSTGRES_PASSWORD: \${POSTGRES_PASSWORD:-change-me-locally}\n    ports:\n      - "5432:5432"\n`;
  }

  private renderArchitecture(name: string, stack: ProjectStack, architecturePreset: ArchitecturePreset): string {
    return `# ${name} Architecture\n\nPreset: ${architecturePreset}\n\nStack: ${stack}\n\n## Components\n\n- Web application\n- API service\n- PostgreSQL metadata store\n`;
  }

  private validateGeneratedFiles(files: { path: string; content: string }[]) {
    const required = ["README.md", "docker-compose.yml", ".env.example", "docs/architecture.md"];
    for (const suffix of required) {
      if (!files.some((file) => file.path.endsWith(suffix))) {
        throw new BadRequestException(`Generated output missing ${suffix}`);
      }
    }
    for (const file of files) {
      if (file.path.startsWith("/") || file.path.includes("..")) {
        throw new BadRequestException(`Unsafe generated path: ${file.path}`);
      }
      if (/(ghp_|sk-|BEGIN (RSA|OPENSSH|PRIVATE) KEY)/.test(file.content)) {
        throw new BadRequestException(`Generated file appears to contain a secret: ${file.path}`);
      }
    }
  }
}
