import {
  GenerateQuickStartRequest,
  GenerateQuickStartResponse,
  QuickStartGeneratedFile,
  QuickStartStack
} from "./quickstart-generator.types";

const SUPPORTED_STACKS: QuickStartStack[] = ["node-http", "node-service", "node-worker-api"];

export class QuickStartGeneratorService {
  getOptions() {
    return {
      edition: "GoneOps QuickStart Edition",
      goal: "One Click Project Bootstrap",
      stacks: SUPPORTED_STACKS.map((stack) => ({
        id: stack,
        label: this.stackLabel(stack),
        description: this.stackDescription(stack)
      })),
      flow: ["select stack", "click generate", "run local project"] as const
    };
  }

  generate(request: GenerateQuickStartRequest = {}): GenerateQuickStartResponse {
    const name = this.normalizeName(request.name ?? "QuickStart App");
    const slug = this.slugify(name);
    const stack = request.stack ?? "node-http";

    if (!SUPPORTED_STACKS.includes(stack)) {
      throw new Error(`Unsupported QuickStart stack: ${stack}`);
    }

    const files: QuickStartGeneratedFile[] = [
      { path: `${slug}/README.md`, content: this.renderReadme(name, slug, stack) },
      { path: `${slug}/package.json`, content: this.renderPackageJson(slug, stack) },
      { path: `${slug}/.env.example`, content: this.renderEnvExample() },
      { path: `${slug}/.gitignore`, content: this.renderGitignore() },
      { path: `${slug}/src/server.js`, content: this.renderServer(stack) },
      { path: `${slug}/Dockerfile`, content: this.renderDockerfile() },
      { path: `${slug}/docker-compose.yml`, content: this.renderDockerCompose() }
    ];

    this.validate(files);

    return {
      edition: "GoneOps QuickStart Edition",
      goal: "One Click Project Bootstrap",
      project: { name, slug, stack },
      flow: ["select stack", "click generate", "run local project"],
      files,
      validation: {
        valid: true,
        checks: [
          "stack selection accepted",
          "hello world endpoint generated",
          "README generated",
          ".env.example generated",
          "Docker Compose generated",
          "ports resolved from .env",
          "local startup command generated",
          "build command generated"
        ]
      }
    };
  }

  private normalizeName(name: string) {
    const normalized = name.trim().replace(/\s+/g, " ");
    if (!normalized) {
      throw new Error("Project name is required");
    }
    if (normalized.length > 80) {
      throw new Error("Project name must be 80 characters or fewer");
    }
    return normalized;
  }

  private slugify(name: string) {
    return name
      .toLowerCase()
      .replace(/[^a-z0-9]+/g, "-")
      .replace(/^-+|-+$/g, "")
      .slice(0, 64);
  }

  private stackLabel(stack: QuickStartStack) {
    return {
      "node-http": "Node HTTP API",
      "node-service": "Node Service API",
      "node-worker-api": "Node Worker API"
    }[stack];
  }

  private stackDescription(stack: QuickStartStack) {
    return {
      "node-http": "Small native Node.js HTTP app with zero runtime dependencies.",
      "node-service": "Clean service-shaped Node.js app for internal APIs.",
      "node-worker-api": "Lightweight worker-friendly API skeleton with a hello endpoint."
    }[stack];
  }

  private renderReadme(name: string, slug: string, stack: QuickStartStack) {
    return `# ${name}

Generated by GoneOps QuickStart Edition.

Goal: One Click Project Bootstrap.

## Stack

${this.stackLabel(stack)}

## Quick Start

\`\`\`bash
cp .env.example .env
npm install
npm run build
npm start
\`\`\`

Open the hello world endpoint:

\`\`\`bash
curl http://localhost:$PORT/hello
\`\`\`

## Docker Compose

\`\`\`bash
cp .env.example .env
docker compose up --build
\`\`\`

## Environment

Ports are configured through .env only. The app reads PORT from the environment. Docker Compose reads APP_PORT and PORT from .env.

## Generated Files

- README.md
- package.json
- .env.example
- src/server.js
- Dockerfile
- docker-compose.yml

## Scope

This QuickStart project intentionally stays simple: stack selection, local project files, Docker Compose, README, .env.example, and a Hello World endpoint.

Project folder: ${slug}
`;
  }

  private renderPackageJson(slug: string, stack: QuickStartStack) {
    return JSON.stringify(
      {
        name: slug,
        version: "0.1.0",
        private: true,
        type: "module",
        description: `GoneOps QuickStart ${this.stackLabel(stack)}`,
        scripts: {
          build: "node --check src/server.js",
          start: "node src/server.js",
          test: "node --test"
        },
        engines: {
          node: ">=22.0.0"
        }
      },
      null,
      2
    ) + "\n";
  }

  private renderEnvExample() {
    return `NODE_ENV=development
PORT=4110
APP_PORT=4110
`;
  }

  private renderGitignore() {
    return `node_modules/
.env
.DS_Store
npm-debug.log*
`;
  }

  private renderServer(stack: QuickStartStack) {
    const serviceName = this.stackLabel(stack);
    return `import http from "node:http";

const port = Number(process.env.PORT);

if (!Number.isInteger(port) || port <= 0) {
  console.error("PORT must be provided through .env or the process environment.");
  process.exit(1);
}

const sendJson = (response, statusCode, body) => {
  response.writeHead(statusCode, { "content-type": "application/json; charset=utf-8" });
  response.end(JSON.stringify(body));
};

const server = http.createServer((request, response) => {
  if (request.method === "GET" && request.url === "/hello") {
    sendJson(response, 200, {
      message: "Hello World from GoneOps QuickStart Edition",
      stack: "${stack}",
      service: "${serviceName}"
    });
    return;
  }

  if (request.method === "GET" && request.url === "/health") {
    sendJson(response, 200, { status: "ok" });
    return;
  }

  sendJson(response, 404, { error: "not_found" });
});

server.listen(port, () => {
  console.log("GoneOps QuickStart listening on port " + process.env.PORT);
});
`;
  }

  private renderDockerfile() {
    return `FROM node:22-alpine
WORKDIR /app
COPY package.json package-lock.json* ./
RUN npm install --omit=dev
COPY src ./src
CMD ["npm", "start"]
`;
  }

  private renderDockerCompose() {
    return `services:
  app:
    build: .
    env_file:
      - .env
    ports:
      - "${"${APP_PORT:?APP_PORT must be set in .env}"}:${"${PORT:?PORT must be set in .env}"}"
`;
  }

  private validate(files: QuickStartGeneratedFile[]) {
    const required = ["README.md", "package.json", ".env.example", "src/server.js", "Dockerfile", "docker-compose.yml"];
    const paths = files.map((file) => file.path);
    for (const requiredPath of required) {
      if (!paths.some((path) => path.endsWith(requiredPath))) {
        throw new Error(`Missing QuickStart generated file: ${requiredPath}`);
      }
    }

    const env = files.find((file) => file.path.endsWith(".env.example"))?.content ?? "";
    const compose = files.find((file) => file.path.endsWith("docker-compose.yml"))?.content ?? "";
    const server = files.find((file) => file.path.endsWith("src/server.js"))?.content ?? "";

    if (!env.includes("PORT=") || !env.includes("APP_PORT=")) {
      throw new Error("QuickStart .env.example must define PORT and APP_PORT");
    }
    if (!compose.includes("${APP_PORT") || !compose.includes("${PORT")) {
      throw new Error("QuickStart docker-compose.yml must resolve ports from .env");
    }
    if (!server.includes("/hello") || !server.includes("process.env.PORT")) {
      throw new Error("QuickStart server must include hello endpoint and env port handling");
    }
    for (const file of files) {
      if (/ghp_|sk-|BEGIN (RSA|OPENSSH|PRIVATE) KEY/.test(file.content)) {
        throw new Error(`Secret-looking token found in generated file ${file.path}`);
      }
    }
  }
}
